export const VOICE_CONVERSATION_COPY = Object.freeze({
  kn:Object.freeze({
    greeting:'ಮತ್ತೆ ಸ್ವಾಗತ. ಇಂದಿನ ಲೆಕ್ಕಕ್ಕೆ ಹೊಸ ಮೊತ್ತಗಳನ್ನು ಸೇರಿಸೋಣ.',
    onboarding:'ನಮಸ್ಕಾರ. ನಾನು ಸಾಥಿ. ನಿಮ್ಮ ವ್ಯಾಪಾರಕ್ಕೆ ಬಂದ ಹಣ ಮತ್ತು ಖರ್ಚನ್ನು ನೆನಪಿಡಲು ಸಹಾಯ ಮಾಡುತ್ತೇನೆ. ನಿಧಾನವಾಗಿ ಮಾತನಾಡಿ. ಉಳಿಸುವ ಮೊದಲು ಪ್ರತಿ ಮೊತ್ತವನ್ನು ಹೇಳಿ ನಿಮ್ಮ ದೃಢೀಕರಣ ಕೇಳುತ್ತೇನೆ. ಪ್ರತಿ ಬಾರಿ ಹೊಸ ಮೊತ್ತಗಳನ್ನು ಮಾತ್ರ ಹೇಳಿ. ಹಣವನ್ನು ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಯಿಂದ ತೆಗೆಯುವುದಿಲ್ಲ.',
    collectionQuestion:'ಈಗ ಸೇರಿಸಬೇಕಾದ ಹೊಸ ಮಾರಾಟದ ಮೊತ್ತ ಎಷ್ಟು? ಇಲ್ಲದಿದ್ದರೆ ಸೊನ್ನೆ ಹೇಳಿ.',
    investmentQuestion:'ಈಗ ಸೇರಿಸಬೇಕಾದ ಹೊಸ ವ್ಯಾಪಾರದ ಖರ್ಚು ಎಷ್ಟು? ಇಲ್ಲದಿದ್ದರೆ ಸೊನ್ನೆ ಹೇಳಿ.',
    collectionLabel:'ಇಂದಿನ ಮಾರಾಟ',
    investmentLabel:'ವ್ಯಾಪಾರದ ಖರ್ಚು',
    collectionListening:'ಇಂದಿನ ಮಾರಾಟದ ಮೊತ್ತವನ್ನು ಕೇಳುತ್ತಿದ್ದೇನೆ…',
    investmentListening:'ವ್ಯಾಪಾರದ ಖರ್ಚಿನ ಮೊತ್ತವನ್ನು ಕೇಳುತ್ತಿದ್ದೇನೆ…',
    heardCollection:(amount) => `ಇಂದಿನ ಮಾರಾಟಕ್ಕೆ ${amount} ರೂಪಾಯಿ ಸೇರಿಸುತ್ತೇನೆ. ಇದು ಸರಿಯೇ?`,
    heardInvestment:(amount) => `ವ್ಯಾಪಾರದ ಖರ್ಚಿಗೆ ${amount} ರೂಪಾಯಿ ಸೇರಿಸುತ್ತೇನೆ. ಇದು ಸರಿಯೇ?`,
    repeatAmount:'ಮೊತ್ತ ಸ್ಪಷ್ಟವಾಗಿಲ್ಲ. ದಯವಿಟ್ಟು ಒಂದು ಮೊತ್ತವನ್ನು ಮಾತ್ರ ಮತ್ತೆ ಹೇಳಿ.',
    confirmTitle:'ನಾನು ಕೇಳಿದ ಮೊತ್ತ ಸರಿಯೇ?',
    yesCorrect:'ಹೌದು, ಸರಿಯಾಗಿದೆ',
    noRepeat:'ಇಲ್ಲ, ಮತ್ತೆ ಹೇಳುತ್ತೇನೆ',
    tapToRetry:'ಮತ್ತೆ ಕೇಳಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
    manualExampleCollection:'ಉದಾಹರಣೆ: ಒಂದು ಸಾವಿರ ಆರು ನೂರು',
    manualExampleInvestment:'ಉದಾಹರಣೆ: ಒಂಬತ್ತು ನೂರು',
    reviewAmount:'ಮೊತ್ತವನ್ನು ಪರಿಶೀಲಿಸಿ'
  }),
  hi:Object.freeze({
    greeting:'फिर से स्वागत है। आज के हिसाब में नई रकम जोड़ते हैं।',
    onboarding:'नमस्ते। मैं साथी हूँ। आपके कारोबार में आए पैसे और खर्च को याद रखने में मदद करूँगा। आराम से बोलें। सेव करने से पहले हर रकम दोहराकर आपकी पुष्टि लूँगा। हर बार केवल नई रकम बताएं। आपके बैंक खाते से पैसे नहीं कटेंगे।',
    collectionQuestion:'अब बिक्री की कितनी नई रकम जोड़नी है? नहीं है तो शून्य बोलें।',
    investmentQuestion:'अब कारोबार के खर्च में कितनी नई रकम जोड़नी है? नहीं है तो शून्य बोलें।',
    collectionLabel:'आज की बिक्री',
    investmentLabel:'कारोबार का खर्च',
    collectionListening:'आज की बिक्री की रकम सुन रहा हूँ…',
    investmentListening:'कारोबार के खर्च की रकम सुन रहा हूँ…',
    heardCollection:(amount) => `आज की बिक्री में ${amount} रुपये जोड़ूँगा। क्या यह सही है?`,
    heardInvestment:(amount) => `कारोबार के खर्च में ${amount} रुपये जोड़ूँगा। क्या यह सही है?`,
    repeatAmount:'रकम साफ़ नहीं थी। कृपया केवल एक रकम फिर से बोलें।',
    confirmTitle:'क्या मैंने रकम सही सुनी?',
    yesCorrect:'हाँ, सही है',
    noRepeat:'नहीं, फिर बोलूँगा',
    tapToRetry:'फिर सुनने के लिए टैप करें',
    manualExampleCollection:'उदाहरण: एक हजार छह सौ',
    manualExampleInvestment:'उदाहरण: नौ सौ',
    reviewAmount:'रकम जाँचें'
  }),
  en:Object.freeze({
    greeting:"Welcome back. Let’s add new amounts to today’s business.",
    onboarding:"Hello, I’m Saathi. I help you remember money coming into and going out of your business. Take your time speaking. I’ll repeat every amount and ask you to confirm before saving. Each time, tell me only new amounts that have not been saved. I do not move money from your bank account.",
    collectionQuestion:'How much new sales money should I add? Say zero if there is none.',
    investmentQuestion:'How much new business spending should I add? Say zero if there is none.',
    collectionLabel:"Today's sales",
    investmentLabel:'Business spending',
    collectionListening:"Listening for today's sales amount…",
    investmentListening:'Listening for the business spending amount…',
    heardCollection:(amount) => `I’ll add ${amount} rupees to today’s sales. Is that correct?`,
    heardInvestment:(amount) => `I’ll add ${amount} rupees to business spending. Is that correct?`,
    repeatAmount:'That amount was not clear. Please say only one amount again.',
    confirmTitle:'Did I hear the amount correctly?',
    yesCorrect:'Yes, correct',
    noRepeat:"No, I'll say it again",
    tapToRetry:'Tap to listen again',
    manualExampleCollection:'Example: one thousand six hundred',
    manualExampleInvestment:'Example: nine hundred',
    reviewAmount:'Review amount'
  })
});
